// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ebavdjmderteydksnwmh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImViYXZkam1kZXJ0ZXlka3Nud21oIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUzNzc4NTMsImV4cCI6MjA2MDk1Mzg1M30.S7Y_PRNnDlkWoSyzlI5_dTK-YCcLZKI4UIANOIf78fs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});